add_executable(${ProjectName})
target_compile_definitions(${ProjectName} PRIVATE Predefine_ResourceDir="D:/video/视频开发测试")
target_import_src(${ProjectName})

target_link_libraries(${ProjectName} PUBLIC -Wl,--start-group)
target_import_boost_asio(${ProjectName} PUBLIC)
target_import_ffmpeg_wrapper(${ProjectName} PUBLIC)
target_import_tsduck(${ProjectName} PUBLIC)
target_import_sdl2_wrapper(${ProjectName} PUBLIC)
target_link_libraries(${ProjectName} PUBLIC -Wl,--end-group)
